### ISSUE TITLE
Kitsunet PoC todo

### ISSUE THREAD

**Issue by dryajov** [MetaMask/kitsunet-js#1]
### Slice tracking and propagation:

- [ ] standup a (kitsunet) node that polls for slices/slice updates and publishes over multiplex
- [ ] subscribe to selected slices over multiplex/pubsub (slices are not persisted)
  - [ ] forward updates to the next node with the following considerations:
     - [ ] we haven't already forwarded the message/slice
     - [ ] verify that the updated/new slice is valid (use current PoW implementations)
       - [ ] if invalid blacklist and disconnect from the peer that forwarded the slice
- [ ] track block header (this can be done using infura or the same RPC calls available in the bridge node)

### Interact with slices:

- [ ] Query accounts for existing slices (a slice is a subset of the ethereum trie)
- [ ] Interact with tokens (requires running contracts in VM)
- [ ] If we have the time, submit transactions over multiplex/pubsub

### Integrate the kitsunet client into MetaMask:
- [ ] Integrate the kitsunet client PoC into the metamask extension for demo purposes
